### ISSUE TITLE
There is no need to parse all *.txt file

### ISSUE THREAD

**Issue by GoldsteinE** [heraldofsolace/VimHelpBot#28]
It's enough to parse tags file, which is simpler and faster

**Comment by heraldofsolace** [comment]
Which tags file are you talking about? If you're referring to the code in `help_tags_extractor` then it parses the txt files and compiles the tags into the database. Those files are parsed and the tags are compiled into a database so it doesn't affect the runtime at all.

**Comment by GoldsteinE** [comment]
Yeah, I'm about tags extractor.
Just saying there's a simpler way to parse tags — from tags file instead of txt file.
`/usr/share/vim/vim<version>/doc/tags` for Vim.

**Comment by heraldofsolace** [comment]
I get it
