### ISSUE TITLE
Triggering bot to rescan updated post

### ISSUE THREAD

**Issue by lieryan** [heraldofsolace/VimHelpBot#29]
Is there a way to tell the bot to rescan your post and update its linked help pages? Sometimes I made a mistake when summoning the bot and linked to an incorrect help page. For example, recently I intended to link to the setting page for statusline, which is `:help 'statusline'`, but the bot linked to the feature list page `:help +statusline`, because I summoned the bot using an ambiguous tag name `:help statusline`. Of course this was my mistake to begin with, since I should've verified the correct tag name before making the post rather than relying on `:help` to guess which help page I meant, but is there a way to have the bot rescan the post after I fixed the original post? Or maybe even better, the bot should automatically rescan any updated posts.

**Comment by heraldofsolace** [comment]
There is no way to scan for updates due to Reddit's limitations itself. I am however working on a way to tell the bot to scan a comment again.

**Comment by heraldofsolace** [comment]
With the recent update, bot now has the ability to rescan comments. Just reply "rescan" to the bot's comment and it will update.
