### ISSUE TITLE
v_CTRL-] response uses invalid old reddit markdown 

### ISSUE THREAD

**Issue by idbrii** [heraldofsolace/VimHelpBot#31]
**Describe the bug**
Response for `v_CTRL-]` help uses invalid old reddit markdown -- the `]` needs to be escaped.

**To Reproduce**
Enter this input
```
See `:h v_CTRL-]`.
```

See example: 

[Broken in old]( https://old.reddit.com/r/vim/comments/j62xmk/vim_and_ctags_make_ctrl_more_useful/g7vxfwa/)
[But works in new](
https://new.reddit.com/r/vim/comments/j62xmk/vim_and_ctags_make_ctrl_more_useful/g7vxfwa/)

**Expected Output**

```
Help pages for:

* [v_CTRL-\]](https://vimhelp.org/tagsrch.txt.html#v_CTRL-%5D) in _tagsrch.txt_
```
(not using `fixed width` since it doesn't let you escape `]` in old reddit.

**Actual Output**

```
Help pages for:

* [`v_CTRL-]`](https://vimhelp.org/tagsrch.txt.html#v_CTRL-%5D) in _tagsrch.txt_
```

**Additional context**

- [ ] Willing to take up?

**Comment by heraldofsolace** [comment]
Thanks for reporting this issue. Do you know of any other texts that could potentially be problematic?

**Comment by idbrii** [comment]
Presumably anything with `]` and possibly with `[`, but I'm not sure. This is the first time I've seen a malformed link from VimHelpBot.

`:help ]<Tab>` shows a bunch of possibilities. I think you'd have to process `:help index` to convert them into links for testing VimHelpBot. Not sure where you can do testing without spamming /r/vim.

**Comment by heraldofsolace** [comment]
This is fixed now
