### ISSUE TITLE
bot linked o_V instead of o_v

### ISSUE THREAD

**Issue by Abraxas-Knister** [heraldofsolace/VimHelpBot#34]
Title, pretty much.

https://www.reddit.com/r/vim/comments/k01f69/unconditional_linewise_or_characterwise_pasting/gdfgc33/?context=3

Absolutely not important since these are neighboring help entries. Still a bug tho

**Comment by Abraxas-Knister** [comment]
Related: [this thread](https://www.reddit.com/r/vim/comments/k01f69/unconditional_linewise_or_characterwise_pasting/gdh1vdb/?context=3) contains some comment of mine (u/abraxasknister) where the bot linked gH instead of gh.

**Comment by heraldofsolace** [comment]
Should be fixed now
