### ISSUE TITLE
Tag "G" behaves as "g"

### ISSUE THREAD

**Issue by Abraxas-Knister** [heraldofsolace/VimHelpBot#35]
:h G

linked to the index of g prefixed commands instead of the G normal mode command.

Found here

https://www.reddit.com/r/vim/comments/m330z4/-/gqmni77

The commenter didn't use code formatting, maybe that has to do with it? 

I noticed a few other instances of case susceptibility but can't make it more specific.

**Comment by heraldofsolace** [comment]
I'm pretty sure their original comment was ":h g" and after the bot replied with "g" they changed their comment to ":h G". The bot replies with the correct page. See here (https://www.reddit.com/r/vim/comments/lxl6ti/vim_documentation_is_the_best/gqn8nsq?utm_source=share&utm_medium=web2x&context=3). They should have called rescan after they edited their comment.

**Comment by Abraxas-Knister** [comment]
Didn't notice the edited flag, sorry for bothering
