### ISSUE TITLE
`:h index` incorrectly links to index.html

### ISSUE THREAD

**Issue by ii14** [heraldofsolace/VimHelpBot#40]
**Describe the bug**
`:h index` and `:h index.txt` recognizes the correct tag, but incorrectly links to [index.html](https://neovim.io/doc/user/index.html#index) instead of [vimindex.html](https://neovim.io/doc/user/vimindex.html).

- [ ] #41

**Comment by heraldofsolace** [comment]
It seems like the tag is indeed in `index.txt`, but the website has renamed the file to be `vimindex.html`, possibly so that it doesn't conflict with `index.html`?

**Comment by ii14** [comment]
Yes, that seems to be the case. `index` just has to be handled as a special case and link to vimindex.

**Comment by heraldofsolace** [comment]
Should be fixed now. Thanks for waiting.
