### ISSUE TITLE
Trouble identifying help for g*

### ISSUE THREAD

**Issue by Gumnos** [heraldofsolace/VimHelpBot#42]
**Describe the bug**

Went to tag help-links for `g*` and `g#` bu putting in `:help g*` and `:help g#`. The bot correctly identified & linked `g#` but missed `g*`.  Vim's internal expansion algorithm turns this into `:help gstar` 

**To Reproduce**

As above, [create a comment in /r/vim containing `:help g*`](https://www.reddit.com/r/vim/comments/t5otew/use_register/hz6a7m4/)

**Expected behavior**

The algorithm uses the same conversion that vim does, turning `g*` into `gstar`

- [] Willing to take up?

**Comment by heraldofsolace** [comment]
Fixed
