### ISSUE TITLE
Bad markdown produced when producing help for g]

### ISSUE THREAD

**Issue by Gumnos** [heraldofsolace/VimHelpBot#43]
**Describe the bug**

Help for `g]` creates broken markdown

**To Reproduce**

Created a comment on /r/vim referring to help for `g]` using `:help g]` 

However, I believe the closing `]` caused issues choking the markup.

**Expected behavior**

A reply containing a proper markdown link. 

**Screenshots**

![2022-06-19-191912_743x156_scrot](https://user-images.githubusercontent.com/1056674/174505958-344622f2-3f51-4843-9396-5e96d79710a9.png)

- [ ] Willing to take up?

**Comment by idbrii** [comment]
I think this is a dupe of #36.

**Comment by Gumnos** [comment]
I agree this appears to be a duplicate of #36
