### ISSUE TITLE
:h synstack() links to wrong help file

### ISSUE THREAD

**Issue by mgedmin** [heraldofsolace/VimHelpBot#44]
**Describe the bug**

Look here: https://www.reddit.com/r/vim/comments/xh15lq/how_to_detect_syntax_region_under_cursor_for/iouzpo2/

**To Reproduce**

1. Write `:help synstack()`, I suppose

You get a link to https://vimhelp.org/eval.txt.html#synstack%28%29 but there's no documentation for `synstack()` there.

**Expected behavior**

A link to https://vimhelp.org/builtin.txt.html#synstack%28%29

- [ ] Willing to take up?

**Comment by heraldofsolace** [comment]
Seems like synstack() was moved from eval to builtin but my database update script only added the "new" entries and didn't delete the non-existent ones. SHould be fixed now.
