### ISSUE TITLE
Syntax with double back tick seems not supported

### ISSUE THREAD

**Issue by kaddkaka** [heraldofsolace/VimHelpBot#46]
**Describe the bug**
The syntax for inline code with double back ticks creates an incorrect link:
```markdown
`` :h `[ ``
```

See reddit post:

- [] Willing to take up?

**Comment by kaddkaka** [comment]
Link to comment that got the incorrect bot response:

https://www.reddit.com/r/vim/comments/z2wzlo/bookmarks_best_practices/ixn7nqr?utm_medium=android_app&utm_source=share&context=3

**Comment by heraldofsolace** [comment]
Should be fixed now.
